import sys
import os
import hashlib

UNIT = 100000000        # The same across currencies.

# Versions
CLIENT_VERSION_MAJOR = 1
CLIENT_VERSION_MINOR = 5
CLIENT_VERSION = float(str(CLIENT_VERSION_MAJOR) + '.' + str(CLIENT_VERSION_MINOR))
DB_VERSION_MAJOR = 1        # Major version changes the blocks or transactions table.
DB_VERSION_MINOR = 5        # Minor version changes just the parsing.
DB_VERSION = float(str(DB_VERSION_MAJOR) + '.' + str(DB_VERSION_MINOR))

# Ports
BITCOIND_RPC_PORT_LIVE = '8332'
BITCOIND_RPC_PORT_TESTNET = '18332'
RPC_HOST = 'localhost'
RPC_PORT_TESTNET = '14000'
RPC_PORT_LIVE = '4000'
BITCOIND_RPC_CONNECT = 'localhost'
BITCOIND_RPC_USER = 'bitcoinrpc'
RPC_USER = 'rpc'

# Testnet, testcoin
TESTNET = False
TESTCOIN = False

# Application name
UNITTEST_PREFIX = b'TESTXXXX'
PREFIX_TESTCOIN = b'CH'
PREFIX_LIVECOIN = b'CHANCECO'
APPAUTHOR = 'Chancecoin'
APPNAME = 'chancecoin'
API_LOG = 'api.error.log'
LOGGING_LOG = 'logging.log'
CONFIG_FILENAME = 'chancecoin.conf'
DATA_DIR_TESTNET = 'chancecoind.testnet.log'
DATA_DIR_LIVE = 'chancecoin.log'
DATABASE_NAME_PREFIX = 'chancecoin'
UNSPENDABLE_TESTNET_TESTCOIN = 'mvChancecoinXXXXXXXXXXXXXXXXW24Hef'
UNSPENDABLE_TESTNET_LIVECOIN = 'mvChancecoinXXXXXXXXXXXXXXXXW24Hef'
UNSPENDABLE_LIVE_TESTCOIN = '1ChancecoinXXXXXXXXXXXXXXXXXZELUFD'
UNSPENDABLE_LIVE_LIVECOIN = '1ChancecoinXXXXXXXXXXXXXXXXXZELUFD'

# Burn period
TESTNET_TESTCOIN_FIRST = 154908
TESTNET_TESTCOIN_START = 154908
TESTNET_TESTCOIN_END = 4017708
TESTNET_LIVECOIN_FIRST = 154908
TESTNET_LIVECOIN_START = 154908
TESTNET_LIVECOIN_END = 4017708
LIVE_TESTCOIN_FIRST = 288270
LIVE_TESTCOIN_START = 288310
LIVE_TESTCOIN_END = 2500000
LIVE_LIVECOIN_FIRST = 291860
LIVE_LIVECOIN_START = LIVE_LIVECOIN_FIRST
LIVE_LIVECOIN_END = LIVE_LIVECOIN_START+6*24*45 #45 days
MAX_BURN = 1000000
MULTIPLIER = 1000
MULTIPLIER_INITIAL = 1500

# Casino
HOUSE_EDGE = 0.02 #0.02 means the house takes 2% edge
MAX_PROFIT = 0.01 #0.01 means most you can win is 1% of the house bankroll

# Bitcoin protocol
# DUST_SIZE = 5430      # OP_RETURN
DUST_SIZE = 5430 * 2    # Multi‐sig (TODO: This is just a guess.)
MIN_FEE = 10000         # Chancecoin transactions are all under 1KB in size.
DATA_VALUE = 0

# Chancecoin protocol
TXTYPE_FORMAT = '>I'

TWO_WEEKS = 2 * 7 * 24 * 3600
MAX_EXPIRATION = 4 * 2016   # Two months

# SQLite3
MAX_INT = 2**63 - 1

# Order fees
FEE_REQUIRED_DEFAULT = .01   # 1%
FEE_PROVIDED_DEFAULT = .01   # 1%
